import RightBar from "@/components/shared/RightBar";
import TopBar from "@/components/shared/TopBar";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import "../globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thread",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <TopBar />

          <main className="flex flex-row">
            <section className="main-container">
              <div className="w-full max-w-4xl">{children}</div>
            </section>

            <RightBar />
          </main>


        </body>
      </html>
    </ClerkProvider>
  )
}
