//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "thread_community")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub thread_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub community_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::community::Entity",
        from = "Column::CommunityId",
        to = "super::community::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Community,
    #[sea_orm(
        belongs_to = "super::thread::Entity",
        from = "Column::ThreadId",
        to = "super::thread::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Thread,
}

impl Related<super::community::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Community.def()
    }
}

impl Related<super::thread::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Thread.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
